services:
  # Banco de Dados PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: aravo_db
    environment:
      POSTGRES_DB: aravo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d aravo_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Servidor de Cache Distribuído
  redis:
    image: redis:7-alpine
    container_name: aravo_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  # Aplicação
  api:
    build: .
    container_name: aravo_api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_URL=jdbc:postgresql://db:5432/aravo_db
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    restart: unless-stopped

volumes:
  postgres_data: