# ===============================
# Config. Banco de Dados
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# Config. JPA / Hibernate
# ===============================
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN

# ===============================
# Config. JWT
# ===============================
api.security.token.secret=${JWT_SECRET}
api.security.token.expiration=${JWT_EXPIRATION}
log