# ===============================
# Config. Banco de Dados
# ===============================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/aravo_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin}

# ===============================
# Config. JPA / Hibernate
# ===============================
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Config. JWT
# ===============================
api.security.token.secret=${JWT_SECRET:HJHKJsadacjhjdf97823bduighHUIGIYGuiu13SDCUIGdev}
api.security.token.expiration=${JWT_EXPIRATION:86400000}

# ===============================
# Config. Cache (Redis)
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ===============================
# Config. Secrets
# ===============================
spring.config.import=optional:classpath:application-secrets.properties
