ALTER TABLE activities DROP COLUMN focus_time;
ALTER TABLE activities RENAME COLUMN points TO points_earned;

ALTER TABLE activities ALTER COLUMN title DROP NOT NULL;
ALTER TABLE activities ALTER COLUMN points_earned DROP NOT NULL;

ALTER TABLE activities
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
    ADD COLUMN start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN end_time TIMESTAMP;